// ============================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/interceptor_demo
spring.datasource.username=postgres
spring.datasource.password=2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=8080